spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/exBoard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
  logging.level:
    org.hibernate.SQL: debug
#     org.hibernate.type: trace

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      location: c:\\Temp\\upload

upload:
  path: c:\\Temp\\upload
